export const jobCategories = [
  "Electrician",
  "Construction",
  "Plumbers",
  "Carpenter",
  "Chef/Cook",
  "Waiters/Waitresses",
  "Bartenders",
  "Housekeeping",
  "Bakers",
  "Warehouse",
  "Factory Workers",
  "Machine Operators",
  "IT",
  "Nurses",
  "Healthcare",
  "Retail",
  "Education",
  "Sales",
  "Marketing",
  "Cashiers",
  "Finance",
  "Drivers",
  "Housemaids",
  "Nannies",
  "Farm Workers",
  "Beauticians",
  "Massage Therapists",
  "Security Guards",
  "Bodyguards",
  "Janitors",
  "Butchers",
  "Food Packers",
  "Others",
];
